/*
 * traO Judge API
 *
 * traO Judge API (front ↔ back)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DevTokens : 開発者トークン一覧
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DevTokens {
    #[serde(rename = "total")]
    pub total: i32,
    #[serde(rename = "devTokens")]
    pub dev_tokens: Vec<models::DevToken>,
}

impl DevTokens {
    /// 開発者トークン一覧
    pub fn new(total: i32, dev_tokens: Vec<models::DevToken>) -> DevTokens {
        DevTokens { total, dev_tokens }
    }
}
