/*
 * traO Judge API
 *
 * traO Judge API (front ↔ back)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DevTokenIssueResponse : 開発者トークン発行レスポンス。 devToken はこのレスポンスでのみ返されます。
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DevTokenIssueResponse {
    /// 開発者トークン。この値はサーバー側に平文保存されません。
    #[serde(rename = "devToken")]
    pub dev_token: String,
    #[serde(rename = "token")]
    pub token: models::DevToken,
}

impl DevTokenIssueResponse {
    /// 開発者トークン発行レスポンス。 devToken はこのレスポンスでのみ返されます。
    pub fn new(dev_token: String, token: models::DevToken) -> DevTokenIssueResponse {
        DevTokenIssueResponse { dev_token, token }
    }
}
