/*
 * traO Judge API
 *
 * traO Judge API (front ↔ back)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DevToken : 開発者トークンの状態
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DevToken {
    /// 開発者トークンID
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    /// 開発者トークンの表示名
    #[serde(rename = "name")]
    pub name: String,
    /// 開発者トークンの発行日時
    #[serde(rename = "createdAt")]
    pub created_at: String,
    /// 開発者トークンの有効期限。発行から約3ヶ月後。
    #[serde(rename = "expiresAt")]
    pub expires_at: String,
    /// 開発者トークンの最終使用日時
    #[serde(
        rename = "lastUsedAt",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub last_used_at: Option<Option<String>>,
}

impl DevToken {
    /// 開発者トークンの状態
    pub fn new(id: uuid::Uuid, name: String, created_at: String, expires_at: String) -> DevToken {
        DevToken {
            id,
            name,
            created_at,
            expires_at,
            last_used_at: None,
        }
    }
}
