/*
 * traO Judge API
 *
 * traO Judge API (front ↔ back)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// EditorialSummary : 解説
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EditorialSummary {
    /// 解説ID
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "problemId")]
    pub problem_id: String,
    /// 作成日時
    #[serde(rename = "createdAt")]
    pub created_at: String,
    /// 更新日時
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
    /// 投稿者のユーザーID
    #[serde(rename = "authorId")]
    pub author_id: String,
    /// 解説が全体公開かどうか.  * `true` - 公開 * `false` - 非公開 (問題の作者のみ閲覧可)
    #[serde(rename = "isPublic")]
    pub is_public: bool,
    #[serde(rename = "title")]
    pub title: String,
}

impl EditorialSummary {
    /// 解説
    pub fn new(
        id: String,
        problem_id: String,
        created_at: String,
        updated_at: String,
        author_id: String,
        is_public: bool,
        title: String,
    ) -> EditorialSummary {
        EditorialSummary {
            id,
            problem_id,
            created_at,
            updated_at,
            author_id,
            is_public,
            title,
        }
    }
}
