/*
 * traO Judge API
 *
 * traO Judge API (front ↔ back)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetGoogleAuthParams200Response {
    #[serde(rename = "url")]
    pub url: String,
}

impl GetGoogleAuthParams200Response {
    pub fn new(url: String) -> GetGoogleAuthParams200Response {
        GetGoogleAuthParams200Response { url }
    }
}
