/*
 * traO Judge API
 *
 * traO Judge API (front ↔ back)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Language : プログラミング言語についての情報
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Language {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name")]
    pub name: String,
}

impl Language {
    /// プログラミング言語についての情報
    pub fn new(id: String, name: String) -> Language {
        Language { id, name }
    }
}
