// @generated by server/traojudge-backend_app/scripts/gen-api.sh from docs/API/front_back.yaml
// Do not edit by hand.
#![allow(
    unused_imports,
    clippy::derive_partial_eq_without_eq,
    clippy::derivable_impls,
    clippy::empty_docs,
    clippy::too_many_arguments,
    reason = "OpenAPI Generator output is regenerated from docs/API/front_back.yaml"
)]

pub mod dev_token;
pub use self::dev_token::DevToken;
pub mod dev_token_issue_response;
pub use self::dev_token_issue_response::DevTokenIssueResponse;
pub mod dev_tokens;
pub use self::dev_tokens::DevTokens;
pub mod editorial;
pub use self::editorial::Editorial;
pub mod editorial_summary;
pub use self::editorial_summary::EditorialSummary;
pub mod email;
pub use self::email::Email;
pub mod get_google_auth_params_200_response;
pub use self::get_google_auth_params_200_response::GetGoogleAuthParams200Response;
pub mod get_google_auth_params_500_response;
pub use self::get_google_auth_params_500_response::GetGoogleAuthParams500Response;
pub mod judge_result;
pub use self::judge_result::JudgeResult;
pub mod judge_status;
pub use self::judge_status::JudgeStatus;
pub mod language;
pub use self::language::Language;
pub mod me;
pub use self::me::Me;
pub mod o_auth_authorization_code;
pub use self::o_auth_authorization_code::OAuthAuthorizationCode;
pub mod post_dev_token_request;
pub use self::post_dev_token_request::PostDevTokenRequest;
pub mod post_editorial_request;
pub use self::post_editorial_request::PostEditorialRequest;
pub mod post_google_o_auth_authorize_200_response;
pub use self::post_google_o_auth_authorize_200_response::PostGoogleOAuthAuthorize200Response;
pub mod post_problem_request;
pub use self::post_problem_request::PostProblemRequest;
pub mod post_problem_update_request;
pub use self::post_problem_update_request::PostProblemUpdateRequest;
pub mod post_problem_update_request_empty_directories_inner;
pub use self::post_problem_update_request_empty_directories_inner::PostProblemUpdateRequestEmptyDirectoriesInner;
pub mod post_problem_update_request_executions_inner;
pub use self::post_problem_update_request_executions_inner::PostProblemUpdateRequestExecutionsInner;
pub mod post_problem_update_request_executions_inner_dependencies_inner;
pub use self::post_problem_update_request_executions_inner_dependencies_inner::PostProblemUpdateRequestExecutionsInnerDependenciesInner;
pub mod post_problem_update_request_runtime_texts_inner;
pub use self::post_problem_update_request_runtime_texts_inner::PostProblemUpdateRequestRuntimeTextsInner;
pub mod post_problem_update_request_texts_inner;
pub use self::post_problem_update_request_texts_inner::PostProblemUpdateRequestTextsInner;
pub mod post_problem_update_response;
pub use self::post_problem_update_response::PostProblemUpdateResponse;
pub mod post_problem_update_response_presigned_urls_inner;
pub use self::post_problem_update_response_presigned_urls_inner::PostProblemUpdateResponsePresignedUrlsInner;
pub mod post_submission_request;
pub use self::post_submission_request::PostSubmissionRequest;
pub mod post_testcase_request_inner;
pub use self::post_testcase_request_inner::PostTestcaseRequestInner;
pub mod problem;
pub use self::problem::Problem;
pub mod problem_summaries;
pub use self::problem_summaries::ProblemSummaries;
pub mod problem_summary;
pub use self::problem_summary::ProblemSummary;
pub mod put_editorial_request;
pub use self::put_editorial_request::PutEditorialRequest;
pub mod put_me_request;
pub use self::put_me_request::PutMeRequest;
pub mod put_password_request;
pub use self::put_password_request::PutPasswordRequest;
pub mod put_problem_request;
pub use self::put_problem_request::PutProblemRequest;
pub mod put_testcase_request;
pub use self::put_testcase_request::PutTestcaseRequest;
pub mod reset_password_request;
pub use self::reset_password_request::ResetPasswordRequest;
pub mod revoke_google_auth_400_response;
pub use self::revoke_google_auth_400_response::RevokeGoogleAuth400Response;
pub mod revoke_traq_auth_400_response;
pub use self::revoke_traq_auth_400_response::RevokeTraqAuth400Response;
pub mod revoke_traq_auth_request;
pub use self::revoke_traq_auth_request::RevokeTraqAuthRequest;
pub mod signup;
pub use self::signup::Signup;
pub mod signup_request;
pub use self::signup_request::SignupRequest;
pub mod submission;
pub use self::submission::Submission;
pub mod submission_summaries;
pub use self::submission_summaries::SubmissionSummaries;
pub mod submission_summary;
pub use self::submission_summary::SubmissionSummary;
pub mod testcase;
pub use self::testcase::Testcase;
pub mod testcase_summary;
pub use self::testcase_summary::TestcaseSummary;
pub mod user;
pub use self::user::User;
pub mod user_authentication;
pub use self::user_authentication::UserAuthentication;
pub mod user_email_and_password;
pub use self::user_email_and_password::UserEmailAndPassword;
pub mod user_global_authority_attribute;
pub use self::user_global_authority_attribute::UserGlobalAuthorityAttribute;

// OpenAPI Generator skips array aliases when generateAliasAsModel=false.
pub type EditorialSummaries = Vec<EditorialSummary>;
pub type PostTestcaseRequest = Vec<PostTestcaseRequestInner>;
pub type TestcaseSummaries = Vec<TestcaseSummary>;
