/*
 * traO Judge API
 *
 * traO Judge API (front ↔ back)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OAuthAuthorizationCode : OAuth先から返される認可コード
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OAuthAuthorizationCode {
    #[serde(rename = "code")]
    pub code: String,
}

impl OAuthAuthorizationCode {
    /// OAuth先から返される認可コード
    pub fn new(code: String) -> OAuthAuthorizationCode {
        OAuthAuthorizationCode { code }
    }
}
