/*
 * traO Judge API
 *
 * traO Judge API (front ↔ back)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostProblemUpdateRequestExecutionsInnerDependenciesInner {
    /// 依存先リソース名
    #[serde(rename = "refTo")]
    pub ref_to: String,
    /// パス環境変数
    #[serde(rename = "pathEnvVar")]
    pub path_env_var: String,
}

impl PostProblemUpdateRequestExecutionsInnerDependenciesInner {
    pub fn new(
        ref_to: String,
        path_env_var: String,
    ) -> PostProblemUpdateRequestExecutionsInnerDependenciesInner {
        PostProblemUpdateRequestExecutionsInnerDependenciesInner {
            ref_to,
            path_env_var,
        }
    }
}
