/*
 * traO Judge API
 *
 * traO Judge API (front ↔ back)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PostProblemUpdateRequest : 問題更新リクエスト
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostProblemUpdateRequest {
    /// 更新時に新たに作成する空ディレクトリのパス一覧
    #[serde(rename = "emptyDirectories")]
    pub empty_directories: Vec<models::PostProblemUpdateRequestEmptyDirectoriesInner>,
    /// 更新時に新たに作成するランタイムテキストファイル一覧
    #[serde(rename = "runtimeTexts")]
    pub runtime_texts: Vec<models::PostProblemUpdateRequestRuntimeTextsInner>,
    /// 更新時に新たに作成するテキストファイル一覧
    #[serde(rename = "texts")]
    pub texts: Vec<models::PostProblemUpdateRequestTextsInner>,
    /// 更新時に新たに作成する実行ファイル一覧
    #[serde(rename = "executions")]
    pub executions: Vec<models::PostProblemUpdateRequestExecutionsInner>,
    /// 更新時に新たに作成するスクリプトファイル一覧
    #[serde(rename = "scripts")]
    pub scripts: Vec<models::PostProblemUpdateRequestTextsInner>,
}

impl PostProblemUpdateRequest {
    /// 問題更新リクエスト
    pub fn new(
        empty_directories: Vec<models::PostProblemUpdateRequestEmptyDirectoriesInner>,
        runtime_texts: Vec<models::PostProblemUpdateRequestRuntimeTextsInner>,
        texts: Vec<models::PostProblemUpdateRequestTextsInner>,
        executions: Vec<models::PostProblemUpdateRequestExecutionsInner>,
        scripts: Vec<models::PostProblemUpdateRequestTextsInner>,
    ) -> PostProblemUpdateRequest {
        PostProblemUpdateRequest {
            empty_directories,
            runtime_texts,
            texts,
            executions,
            scripts,
        }
    }
}
