/*
 * traO Judge API
 *
 * traO Judge API (front ↔ back)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostProblemUpdateRequestExecutionsInner {
    /// リソース名
    #[serde(rename = "name")]
    pub name: String,
    /// スクリプト名
    #[serde(rename = "scriptName")]
    pub script_name: String,
    #[serde(rename = "dependencies")]
    pub dependencies: Vec<models::PostProblemUpdateRequestExecutionsInnerDependenciesInner>,
    /// 実行時間予約(ms)
    #[serde(rename = "timeReservedMs")]
    pub time_reserved_ms: i32,
}

impl PostProblemUpdateRequestExecutionsInner {
    pub fn new(
        name: String,
        script_name: String,
        dependencies: Vec<models::PostProblemUpdateRequestExecutionsInnerDependenciesInner>,
        time_reserved_ms: i32,
    ) -> PostProblemUpdateRequestExecutionsInner {
        PostProblemUpdateRequestExecutionsInner {
            name,
            script_name,
            dependencies,
            time_reserved_ms,
        }
    }
}
