/*
 * traO Judge API
 *
 * traO Judge API (front ↔ back)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PostProblemRequest : 問題の投稿リクエスト
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostProblemRequest {
    /// 問題タイトル
    #[serde(rename = "title")]
    pub title: String,
    /// 難易度
    #[serde(rename = "difficulty")]
    pub difficulty: i32,
    /// 問題文 (HTML形式)
    #[serde(rename = "statement")]
    pub statement: String,
    /// 実行時間制限 (ms)
    #[serde(rename = "timeLimit")]
    pub time_limit: i32,
    /// メモリ制限 (MiB)
    #[serde(rename = "memoryLimit")]
    pub memory_limit: i32,
}

impl PostProblemRequest {
    /// 問題の投稿リクエスト
    pub fn new(
        title: String,
        difficulty: i32,
        statement: String,
        time_limit: i32,
        memory_limit: i32,
    ) -> PostProblemRequest {
        PostProblemRequest {
            title,
            difficulty,
            statement,
            time_limit,
            memory_limit,
        }
    }
}
