/*
 * traO Judge API
 *
 * traO Judge API (front ↔ back)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PostEditorialRequest : 解説の作成リクエスト
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostEditorialRequest {
    /// 解説タイトル
    #[serde(rename = "title")]
    pub title: String,
    /// 解説本文 (HTML)
    #[serde(rename = "statement")]
    pub statement: String,
    /// 解説が全体公開かどうか.  * `true` - 公開 * `false` - 非公開 (問題の作者のみ閲覧可)
    #[serde(rename = "isPublic")]
    pub is_public: bool,
    #[serde(rename = "problemId")]
    pub problem_id: String,
}

impl PostEditorialRequest {
    /// 解説の作成リクエスト
    pub fn new(
        title: String,
        statement: String,
        is_public: bool,
        problem_id: String,
    ) -> PostEditorialRequest {
        PostEditorialRequest {
            title,
            statement,
            is_public,
            problem_id,
        }
    }
}
