/*
 * traO Judge API
 *
 * traO Judge API (front ↔ back)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostProblemUpdateRequestRuntimeTextsInner {
    /// リソース名
    #[serde(rename = "name")]
    pub name: String,
    /// ラベル
    #[serde(rename = "label")]
    pub label: String,
}

impl PostProblemUpdateRequestRuntimeTextsInner {
    pub fn new(name: String, label: String) -> PostProblemUpdateRequestRuntimeTextsInner {
        PostProblemUpdateRequestRuntimeTextsInner { name, label }
    }
}
