/*
 * traO Judge API
 *
 * traO Judge API (front ↔ back)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostProblemUpdateRequestEmptyDirectoriesInner {
    /// リソース名
    #[serde(rename = "name")]
    pub name: String,
}

impl PostProblemUpdateRequestEmptyDirectoriesInner {
    pub fn new(name: String) -> PostProblemUpdateRequestEmptyDirectoriesInner {
        PostProblemUpdateRequestEmptyDirectoriesInner { name }
    }
}
