/*
 * traO Judge API
 *
 * traO Judge API (front ↔ back)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostTestcaseRequestInner {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "testInput")]
    pub test_input: String,
    #[serde(rename = "testOutput")]
    pub test_output: String,
}

impl PostTestcaseRequestInner {
    pub fn new(name: String, test_input: String, test_output: String) -> PostTestcaseRequestInner {
        PostTestcaseRequestInner {
            name,
            test_input,
            test_output,
        }
    }
}
