/*
 * traO Judge API
 *
 * traO Judge API (front ↔ back)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostProblemUpdateResponsePresignedUrlsInner {
    /// リソース名
    #[serde(rename = "resourceName")]
    pub resource_name: String,
    /// アップロード先URL
    #[serde(rename = "url")]
    pub url: String,
}

impl PostProblemUpdateResponsePresignedUrlsInner {
    pub fn new(resource_name: String, url: String) -> PostProblemUpdateResponsePresignedUrlsInner {
        PostProblemUpdateResponsePresignedUrlsInner { resource_name, url }
    }
}
