/*
 * traO Judge API
 *
 * traO Judge API (front ↔ back)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PostProblemUpdateResponse : 問題更新レスポンス
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostProblemUpdateResponse {
    /// 問題更新プロセスのID
    #[serde(rename = "updateId")]
    pub update_id: String,
    /// 問題更新に必要なファイルのアップロード先URL一覧
    #[serde(rename = "presignedUrls")]
    pub presigned_urls: Vec<models::PostProblemUpdateResponsePresignedUrlsInner>,
}

impl PostProblemUpdateResponse {
    /// 問題更新レスポンス
    pub fn new(
        update_id: String,
        presigned_urls: Vec<models::PostProblemUpdateResponsePresignedUrlsInner>,
    ) -> PostProblemUpdateResponse {
        PostProblemUpdateResponse {
            update_id,
            presigned_urls,
        }
    }
}
