/*
 * traO Judge API
 *
 * traO Judge API (front ↔ back)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

use serde_with::serde_as;

/// PostSubmissionRequest : 回答の提出リクエスト
#[serde_as]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostSubmissionRequest {
    /// 提出コードの言語ID
    #[serde(rename = "languageId")]
    pub language_id: String,
    /// ソースコード（base64 encoded string）
    #[serde_as(as = "serde_with::base64::Base64")]
    #[serde(rename = "source")]
    pub source: Vec<u8>,
}

impl PostSubmissionRequest {
    /// 回答の提出リクエスト
    pub fn new(language_id: String, source: Vec<u8>) -> PostSubmissionRequest {
        PostSubmissionRequest {
            language_id,
            source,
        }
    }
}
