/*
 * traO Judge API
 *
 * traO Judge API (front ↔ back)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PostDevTokenRequest : 開発者トークン発行リクエスト
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostDevTokenRequest {
    /// 開発者トークンの表示名
    #[serde(rename = "name")]
    pub name: String,
}

impl PostDevTokenRequest {
    /// 開発者トークン発行リクエスト
    pub fn new(name: String) -> PostDevTokenRequest {
        PostDevTokenRequest { name }
    }
}
