/*
 * traO Judge API
 *
 * traO Judge API (front ↔ back)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostProblemUpdateRequestTextsInner {
    /// リソース名
    #[serde(rename = "name")]
    pub name: String,
    /// ファイルのハッシュ値(SHA256)
    #[serde(rename = "hash")]
    pub hash: String,
}

impl PostProblemUpdateRequestTextsInner {
    pub fn new(name: String, hash: String) -> PostProblemUpdateRequestTextsInner {
        PostProblemUpdateRequestTextsInner { name, hash }
    }
}
