/*
 * traO Judge API
 *
 * traO Judge API (front ↔ back)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Problem : 問題の詳細
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Problem {
    /// 問題ID
    #[serde(rename = "id")]
    pub id: String,
    /// 問題タイトル
    #[serde(rename = "title")]
    pub title: String,
    /// 作問者のユーザーID
    #[serde(rename = "authorId")]
    pub author_id: uuid::Uuid,
    /// 問題が全体公開かどうか.  * `true` - 公開 * `false` - 非公開 (問題の作者のみ閲覧可)
    #[serde(rename = "isPublic")]
    pub is_public: bool,
    /// 難易度
    #[serde(rename = "difficulty")]
    pub difficulty: i32,
    /// 問題文 (HTML形式)
    #[serde(rename = "statement")]
    pub statement: String,
    /// 実行時間制限 (ms)
    #[serde(rename = "timeLimit")]
    pub time_limit: i32,
    /// メモリ制限 (MiB)
    #[serde(rename = "memoryLimit")]
    pub memory_limit: i32,
    #[serde(rename = "solvedCount")]
    pub solved_count: i32,
    #[serde(rename = "testcases")]
    pub testcases: Vec<models::TestcaseSummary>,
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
}

impl Problem {
    /// 問題の詳細
    pub fn new(
        id: String,
        title: String,
        author_id: uuid::Uuid,
        is_public: bool,
        difficulty: i32,
        statement: String,
        time_limit: i32,
        memory_limit: i32,
        solved_count: i32,
        testcases: Vec<models::TestcaseSummary>,
        created_at: String,
        updated_at: String,
    ) -> Problem {
        Problem {
            id,
            title,
            author_id,
            is_public,
            difficulty,
            statement,
            time_limit,
            memory_limit,
            solved_count,
            testcases,
            created_at,
            updated_at,
        }
    }
}
