/*
 * traO Judge API
 *
 * traO Judge API (front ↔ back)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProblemSummaries {
    #[serde(rename = "total")]
    pub total: i32,
    #[serde(rename = "problems")]
    pub problems: Vec<models::ProblemSummary>,
}

impl ProblemSummaries {
    pub fn new(total: i32, problems: Vec<models::ProblemSummary>) -> ProblemSummaries {
        ProblemSummaries { total, problems }
    }
}
