/*
 * traO Judge API
 *
 * traO Judge API (front ↔ back)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PutMeRequest {
    #[serde(rename = "userName")]
    pub user_name: String,
    #[serde(rename = "icon", skip_serializing_if = "Option::is_none")]
    pub icon: Option<std::path::PathBuf>,
    #[serde(rename = "xId")]
    pub x_id: String,
    #[serde(rename = "githubId")]
    pub github_id: String,
    #[serde(rename = "selfIntroduction")]
    pub self_introduction: String,
}

impl PutMeRequest {
    pub fn new(
        user_name: String,
        x_id: String,
        github_id: String,
        self_introduction: String,
    ) -> PutMeRequest {
        PutMeRequest {
            user_name,
            icon: None,
            x_id,
            github_id,
            self_introduction,
        }
    }
}
