/*
 * traO Judge API
 *
 * traO Judge API (front ↔ back)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PutTestcaseRequest : 単体のテストケースの編集
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PutTestcaseRequest {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "testInput")]
    pub test_input: String,
    #[serde(rename = "testOutput")]
    pub test_output: String,
}

impl PutTestcaseRequest {
    /// 単体のテストケースの編集
    pub fn new(name: String, test_input: String, test_output: String) -> PutTestcaseRequest {
        PutTestcaseRequest {
            name,
            test_input,
            test_output,
        }
    }
}
