/*
 * traO Judge API
 *
 * traO Judge API (front ↔ back)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PutProblemRequest : 問題の変更リクエスト
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PutProblemRequest {
    /// 問題タイトル
    #[serde(rename = "title")]
    pub title: String,
    /// 問題が全体公開かどうか.  * `true` - 公開 * `false` - 非公開 (問題の作者のみ閲覧可)
    #[serde(rename = "isPublic")]
    pub is_public: bool,
    /// 難易度
    #[serde(rename = "difficulty")]
    pub difficulty: i32,
    /// 問題文 (HTML形式)
    #[serde(rename = "statement", skip_serializing_if = "Option::is_none")]
    pub statement: Option<String>,
    /// 実行時間制限 (ms)
    #[serde(rename = "timeLimit")]
    pub time_limit: i32,
    /// メモリ制限 (MiB)
    #[serde(rename = "memoryLimit")]
    pub memory_limit: i32,
}

impl PutProblemRequest {
    /// 問題の変更リクエスト
    pub fn new(
        title: String,
        is_public: bool,
        difficulty: i32,
        time_limit: i32,
        memory_limit: i32,
    ) -> PutProblemRequest {
        PutProblemRequest {
            title,
            is_public,
            difficulty,
            statement: None,
            time_limit,
            memory_limit,
        }
    }
}
