/*
 * traO Judge API
 *
 * traO Judge API (front ↔ back)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PutPasswordRequest : ログイン後のパスワード変更用
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PutPasswordRequest {
    #[serde(rename = "oldPassword")]
    pub old_password: String,
    #[serde(rename = "newPassword")]
    pub new_password: String,
}

impl PutPasswordRequest {
    /// ログイン後のパスワード変更用
    pub fn new(old_password: String, new_password: String) -> PutPasswordRequest {
        PutPasswordRequest {
            old_password,
            new_password,
        }
    }
}
