/*
 * traO Judge API
 *
 * traO Judge API (front ↔ back)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PutEditorialRequest : 解説の変更リクエスト.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PutEditorialRequest {
    /// 解説タイトル
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    /// 解説本文 (HTML)
    #[serde(rename = "statement", skip_serializing_if = "Option::is_none")]
    pub statement: Option<String>,
    /// 公開されているかどうか
    #[serde(rename = "isPublic", skip_serializing_if = "Option::is_none")]
    pub is_public: Option<bool>,
}

impl PutEditorialRequest {
    /// 解説の変更リクエスト.
    pub fn new() -> PutEditorialRequest {
        PutEditorialRequest {
            title: None,
            statement: None,
            is_public: None,
        }
    }
}
