/*
 * traO Judge API
 *
 * traO Judge API (front ↔ back)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ResetPasswordRequest :
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ResetPasswordRequest {
    #[serde(rename = "password")]
    pub password: String,
    /// パスワードリセット用のone-time token
    #[serde(rename = "token")]
    pub token: String,
}

impl ResetPasswordRequest {
    ///
    pub fn new(password: String, token: String) -> ResetPasswordRequest {
        ResetPasswordRequest { password, token }
    }
}
