/*
 * traO Judge API
 *
 * traO Judge API (front ↔ back)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RevokeTraqAuthRequest {
    /// The access token to revoke
    #[serde(rename = "token")]
    pub token: String,
}

impl RevokeTraqAuthRequest {
    pub fn new(token: String) -> RevokeTraqAuthRequest {
        RevokeTraqAuthRequest { token }
    }
}
