/*
 * traO Judge API
 *
 * traO Judge API (front ↔ back)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Role : ユーザの役割  * `Admin` - Admin * `traPUser` - AdminでないtraP部員 * `CommonUser` - Adminでない一般ユーザー(traP部員以外のユーザー)
/// ユーザの役割  * `Admin` - Admin * `traPUser` - AdminでないtraP部員 * `CommonUser` - Adminでない一般ユーザー(traP部員以外のユーザー)
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Role {
    #[serde(rename = "Admin")]
    Admin,
    #[serde(rename = "traPUser")]
    TraPUser,
    #[serde(rename = "CommonUser")]
    CommonUser,
}

impl std::fmt::Display for Role {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Admin => write!(f, "Admin"),
            Self::TraPUser => write!(f, "traPUser"),
            Self::CommonUser => write!(f, "CommonUser"),
        }
    }
}

impl Default for Role {
    fn default() -> Role {
        Self::Admin
    }
}
