/*
 * traO Judge API
 *
 * traO Judge API (front ↔ back)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SignupRequest : Signupのリクエスト
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SignupRequest {
    #[serde(rename = "email")]
    pub email: String,
}

impl SignupRequest {
    /// Signupのリクエスト
    pub fn new(email: String) -> SignupRequest {
        SignupRequest { email }
    }
}
