/*
 * traO Judge API
 *
 * traO Judge API (front ↔ back)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Signup : email+password登録
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Signup {
    #[serde(rename = "userName")]
    pub user_name: String,
    #[serde(rename = "password", skip_serializing_if = "Option::is_none")]
    pub password: Option<String>,
    /// メール認証またはOAuth登録のone-time token
    #[serde(rename = "token")]
    pub token: String,
}

impl Signup {
    /// email+password登録
    pub fn new(user_name: String, token: String) -> Signup {
        Signup {
            user_name,
            password: None,
            token,
        }
    }
}
