/*
 * traO Judge API
 *
 * traO Judge API (front ↔ back)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SubmissionSummaries : 提出一覧
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SubmissionSummaries {
    #[serde(rename = "total")]
    pub total: i32,
    #[serde(rename = "submissions")]
    pub submissions: Vec<models::SubmissionSummary>,
}

impl SubmissionSummaries {
    /// 提出一覧
    pub fn new(total: i32, submissions: Vec<models::SubmissionSummary>) -> SubmissionSummaries {
        SubmissionSummaries { total, submissions }
    }
}
