/*
 * traO Judge API
 *
 * traO Judge API (front ↔ back)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

use serde_with::serde_as;

/// Submission : 提出の詳細
#[serde_as]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Submission {
    /// 提出ID
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "title")]
    pub title: String,
    /// 提出ユーザーID
    #[serde(rename = "userId")]
    pub user_id: String,
    #[serde(rename = "userName")]
    pub user_name: String,
    /// 問題ID
    #[serde(rename = "problemId")]
    pub problem_id: String,
    /// 提出コード（base64 encoded string）
    #[serde_as(as = "serde_with::base64::Base64")]
    #[serde(rename = "sourceCode")]
    pub source_code: Vec<u8>,
    /// 提出日時
    #[serde(rename = "submittedAt")]
    pub submitted_at: String,
    /// スコアの合計
    #[serde(rename = "totalScore")]
    pub total_score: i32,
    /// 提出コードの言語ID
    #[serde(rename = "languageId")]
    pub language_id: String,
    /// 実行時間の最大値 (ms)
    #[serde(rename = "maxTime")]
    pub max_time: i32,
    /// メモリ使用量の最大値 (MiB)
    #[serde(rename = "maxMemory")]
    pub max_memory: f64,
    /// base64 decode 後の提出 source bundle のバイト長。複数ファイル提出では zip のバイト長。
    #[serde(rename = "codeLength")]
    pub code_length: i32,
    #[serde(rename = "overallJudgeStatus")]
    pub overall_judge_status: models::JudgeStatus,
    /// 現在の judge run における進捗段階
    #[serde(rename = "judgeProgressStep")]
    pub judge_progress_step: i32,
    /// WJ 中は空配列
    #[serde(rename = "judgeResults")]
    pub judge_results: Vec<models::JudgeResult>,
}

impl Submission {
    /// 提出の詳細
    pub fn new(
        id: String,
        title: String,
        user_id: String,
        user_name: String,
        problem_id: String,
        source_code: Vec<u8>,
        submitted_at: String,
        total_score: i32,
        language_id: String,
        max_time: i32,
        max_memory: f64,
        code_length: i32,
        overall_judge_status: models::JudgeStatus,
        judge_progress_step: i32,
        judge_results: Vec<models::JudgeResult>,
    ) -> Submission {
        Submission {
            id,
            title,
            user_id,
            user_name,
            problem_id,
            source_code,
            submitted_at,
            total_score,
            language_id,
            max_time,
            max_memory,
            code_length,
            overall_judge_status,
            judge_progress_step,
            judge_results,
        }
    }
}
