/*
 * traO Judge API
 *
 * traO Judge API (front ↔ back)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SubmissionSummary : 提出
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SubmissionSummary {
    /// 提出ID
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "title")]
    pub title: String,
    /// 提出ユーザーID
    #[serde(rename = "userId")]
    pub user_id: String,
    #[serde(rename = "userName")]
    pub user_name: String,
    /// 問題ID
    #[serde(rename = "problemId")]
    pub problem_id: String,
    /// 提出日時
    #[serde(rename = "submittedAt")]
    pub submitted_at: String,
    /// 提出コードの言語ID
    #[serde(rename = "languageId")]
    pub language_id: String,
    /// スコアの合計
    #[serde(rename = "totalScore")]
    pub total_score: i32,
    /// 実行時間の最大値 (ms)
    #[serde(rename = "maxTime")]
    pub max_time: i32,
    /// メモリ使用量の最大値 (MiB)
    #[serde(rename = "maxMemory")]
    pub max_memory: f64,
    /// 提出 source bundle のバイト長
    #[serde(rename = "codeLength")]
    pub code_length: i32,
    #[serde(rename = "judgeStatus")]
    pub judge_status: models::JudgeStatus,
    /// 現在の judge run における進捗段階
    #[serde(rename = "judgeProgressStep")]
    pub judge_progress_step: i32,
}

impl SubmissionSummary {
    /// 提出
    pub fn new(
        id: String,
        title: String,
        user_id: String,
        user_name: String,
        problem_id: String,
        submitted_at: String,
        language_id: String,
        total_score: i32,
        max_time: i32,
        max_memory: f64,
        code_length: i32,
        judge_status: models::JudgeStatus,
        judge_progress_step: i32,
    ) -> SubmissionSummary {
        SubmissionSummary {
            id,
            title,
            user_id,
            user_name,
            problem_id,
            submitted_at,
            language_id,
            total_score,
            max_time,
            max_memory,
            code_length,
            judge_status,
            judge_progress_step,
        }
    }
}
