/*
 * traO Judge API
 *
 * traO Judge API (front ↔ back)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Testcase : テストケース
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Testcase {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "testInput")]
    pub test_input: String,
    #[serde(rename = "testOutput")]
    pub test_output: String,
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
}

impl Testcase {
    /// テストケース
    pub fn new(
        name: String,
        id: String,
        test_input: String,
        test_output: String,
        created_at: String,
        updated_at: String,
    ) -> Testcase {
        Testcase {
            name,
            id,
            test_input,
            test_output,
            created_at,
            updated_at,
        }
    }
}
