/*
 * traO Judge API
 *
 * traO Judge API (front ↔ back)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// User : ユーザー情報
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct User {
    /// ユーザーID
    #[serde(rename = "id")]
    pub id: String,
    /// ユーザー名
    #[serde(rename = "name")]
    pub name: String,
    /// traQのID
    #[serde(rename = "traqId", skip_serializing_if = "Option::is_none")]
    pub traq_id: Option<String>,
    /// GitHubのID
    #[serde(rename = "githubId", skip_serializing_if = "Option::is_none")]
    pub github_id: Option<String>,
    #[serde(rename = "iconUrl", skip_serializing_if = "Option::is_none")]
    pub icon_url: Option<String>,
    #[serde(rename = "postProblems", skip_serializing_if = "Option::is_none")]
    pub post_problems: Option<models::ProblemSummaries>,
    #[serde(rename = "submitProblems", skip_serializing_if = "Option::is_none")]
    pub submit_problems: Option<models::SubmissionSummaries>,
    #[serde(rename = "xId", skip_serializing_if = "Option::is_none")]
    pub x_id: Option<String>,
    #[serde(rename = "selfIntroduction", skip_serializing_if = "Option::is_none")]
    pub self_introduction: Option<String>,
    #[serde(rename = "role")]
    pub role: models::Role,
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
}

impl User {
    /// ユーザー情報
    pub fn new(
        id: String,
        name: String,
        role: models::Role,
        created_at: String,
        updated_at: String,
    ) -> User {
        User {
            id,
            name,
            traq_id: None,
            github_id: None,
            icon_url: None,
            post_problems: None,
            submit_problems: None,
            x_id: None,
            self_introduction: None,
            role,
            created_at,
            updated_at,
        }
    }
}
