/*
 * traO Judge API
 *
 * traO Judge API (front ↔ back)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UserAuthentication : ユーザーの認証情報
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserAuthentication {
    /// メール認証用のアドレス（存在すればメール認証可能）
    #[serde(
        rename = "emailAuth",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub email_auth: Option<Option<String>>,
    /// Google認証に使用されているメールアドレス（存在すればGoogle認証済み）
    #[serde(
        rename = "googleAuth",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub google_auth: Option<Option<String>>,
    /// GitHub認証に使用されている識別子（存在すればGitHub認証済み）
    #[serde(
        rename = "githubAuth",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub github_auth: Option<Option<String>>,
    /// traQ認証に使用されている識別子（存在すればtraQ認証済み）
    #[serde(
        rename = "traqAuth",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub traq_auth: Option<Option<String>>,
}

impl UserAuthentication {
    /// ユーザーの認証情報
    pub fn new() -> UserAuthentication {
        UserAuthentication {
            email_auth: None,
            google_auth: None,
            github_auth: None,
            traq_auth: None,
        }
    }
}
