/*
 * traO Judge API
 *
 * traO Judge API (front ↔ back)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UserEmailAndPassword : login
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserEmailAndPassword {
    #[serde(rename = "email")]
    pub email: String,
    #[serde(rename = "password")]
    pub password: String,
}

impl UserEmailAndPassword {
    /// login
    pub fn new(email: String, password: String) -> UserEmailAndPassword {
        UserEmailAndPassword { email, password }
    }
}
