/*
 * traO Judge API
 *
 * traO Judge API (front ↔ back)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UserGlobalAuthorityAttribute : ユーザーのグローバル権限属性
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserGlobalAuthorityAttribute {
    /// システム管理者として扱うか
    #[serde(rename = "isSystemAdmin")]
    pub is_system_admin: bool,
    /// 問題を作成できるか
    #[serde(rename = "canCreateProblem")]
    pub can_create_problem: bool,
    /// traP部員として扱うか
    #[serde(rename = "isTrapUser")]
    pub is_trap_user: bool,
}

impl UserGlobalAuthorityAttribute {
    /// ユーザーのグローバル権限属性
    pub fn new(
        is_system_admin: bool,
        can_create_problem: bool,
        is_trap_user: bool,
    ) -> UserGlobalAuthorityAttribute {
        UserGlobalAuthorityAttribute {
            is_system_admin,
            can_create_problem,
            is_trap_user,
        }
    }
}
