#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
APP_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
ROOT_DIR="$(cd "$APP_DIR/../.." && pwd)"

MODE="${1:-write}"

if [[ "$MODE" != "write" && "$MODE" != "--check" ]]; then
  echo "Usage: $0 [--check]" >&2
  exit 2
fi

OPENAPI_SCHEMA="$ROOT_DIR/docs/API/front_back.yaml"
OUTPUT_DIR="$APP_DIR/src/models"
TMP_DIR="$(mktemp -d)"
TMP_GEN_DIR="$TMP_DIR/openapi"
TMP_MODELS_DIR="$TMP_DIR/models"

cleanup() {
  rm -rf "$TMP_DIR"
}
trap cleanup EXIT

generate_mod_rs() {
  local models_dir="$1"
  local mod_file="$models_dir/mod.rs"

  {
    echo "// @generated by server/traojudge-backend_app/scripts/gen-api.sh from docs/API/front_back.yaml"
    echo "// Do not edit by hand."
    echo "#![allow("
    echo "    unused_imports,"
    echo "    clippy::derive_partial_eq_without_eq,"
    echo "    clippy::derivable_impls,"
    echo "    clippy::empty_docs,"
    echo "    clippy::too_many_arguments,"
    echo "    reason = \"OpenAPI Generator output is regenerated from docs/API/front_back.yaml\""
    echo ")]"
    echo

    for file in "$models_dir"/*.rs; do
      local module_name
      module_name="$(basename "$file" .rs)"

      if [[ "$module_name" == "mod" ]]; then
        continue
      fi

      echo "pub mod $module_name;"

      while IFS= read -r type_name; do
        echo "pub use self::$module_name::$type_name;"
      done < <(sed -nE 's/^pub (struct|enum) ([A-Za-z][A-Za-z0-9_]*).*/\2/p' "$file")
    done

    echo
    echo "// OpenAPI Generator skips array aliases when generateAliasAsModel=false."
    echo "pub type EditorialSummaries = Vec<EditorialSummary>;"
    echo "pub type PostTestcaseRequest = Vec<PostTestcaseRequestInner>;"
    echo "pub type TestcaseSummaries = Vec<TestcaseSummary>;"
  } >"$mod_file"
}

mkdir -p "$TMP_MODELS_DIR"

(
  cd "$APP_DIR"
  npx @openapitools/openapi-generator-cli generate \
    -i "$OPENAPI_SCHEMA" \
    -g rust \
    -o "$TMP_GEN_DIR" \
    --global-property=models,modelDocs=false,modelTests=false,apis=false,supportingFiles=false \
    --additional-properties=packageName=traojudge_backend_openapi,packageVersion=0.1.0,avoidBoxedModels=true,useSingleRequestParameter=true
)

if ! compgen -G "$TMP_GEN_DIR/src/models/*.rs" >/dev/null; then
  echo "OpenAPI Generator did not produce Rust model files" >&2
  exit 1
fi

cp "$TMP_GEN_DIR/src/models/"*.rs "$TMP_MODELS_DIR/"
generate_mod_rs "$TMP_MODELS_DIR"
rustfmt --edition 2024 "$TMP_MODELS_DIR"/*.rs

if [[ "$MODE" == "--check" ]]; then
  if ! diff -ru "$OUTPUT_DIR" "$TMP_MODELS_DIR" >&2; then
    echo "Generated OpenAPI models are out of date. Run server/traojudge-backend_app/scripts/gen-api.sh" >&2
    exit 1
  fi

  echo "Generated OpenAPI models are up to date: $OUTPUT_DIR"
else
  rm -rf "$OUTPUT_DIR"
  mkdir -p "$(dirname "$OUTPUT_DIR")"
  cp -R "$TMP_MODELS_DIR" "$OUTPUT_DIR"

  echo "Generated $OUTPUT_DIR"
fi
