{ flake-parts-lib, ... }:
{
  options.perSystem = flake-parts-lib.mkPerSystemOption (
    { lib, ... }:
    with lib;
    {
      options.trao.languages = mkOption {
        type = types.lazyAttrsOf (
          types.submodule (
            { config, ... }:
            {
              options = {
                builder = mkOption {
                  type = types.functionTo types.package;
                  description = "Represents compile-phase. { source: string } -> package";
                };
                prebuildSourceFile = mkOption {
                  type = types.path;
                  description = "A sample source code file for prebuilding.";
                };
                internal.prebuild = mkOption {
                  type = types.package;
                  description = "The built package for the prebuild source code. Generated by the module.";
                };
                displayName = mkOption {
                  type = types.str;
                  description = "A human-readable name for the language.";
                };
                extension = mkOption {
                  type = types.str;
                  description = "The file extension for source files in this language.";
                };
                checks = mkOption {
                  type = types.lazyAttrsOf (
                    types.submodule (
                      { ... }:
                      {
                        options = {
                          sourceFile = mkOption {
                            type = types.path;
                            description = "The source code to run the check against.";
                          };
                          input = mkOption {
                            type = types.str;
                            description = "The input to provide to the program.";
                          };
                          expectedOutput = mkOption {
                            type = types.str;
                            description = "The expected output from the program.";
                          };
                        };
                      }
                    )
                  );
                  description = "A set of checks to validate the builder.";
                };
              };
              config = {
                internal.sampleBuild = config.builder config.sampleSource;
              };
            }
          )
        );
        default = { };
      };
    }
  );
}
