[package]
name = "traojudge-backend_app"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
axum.workspace = true
serde.workspace = true
serde_with.workspace = true
tokio.workspace = true
tower-http.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
traojudge-core.workspace = true
traojudge-infra.workspace = true
uuid.workspace = true
