[package]
name = "traojudge-infra"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
sqlx.workspace = true
traojudge-core.workspace = true
anyhow.workspace = true
async-trait.workspace = true
tokio = { workspace = true, features = ["fs", "io-util"] }
uuid.workspace = true
